// Columns: id | name (projectName) | client | pm | budget | tasks | hours | duration | status
export const SAMPLE_PROJECTS = [
  {
    rowId: "J01042",
    atRisk: false,
    location: "Wellington",
    row: [
      { value: "J01042",                         type: "text"        },
      { value: "Harbour Point Website Redesign", type: "projectName", meta: { progress: 68 } },
      { value: "Harbour Point Ltd",              type: "text"        },
      { value: "Aroha Smith",                    type: "pm"          },
      { value: "$40,000",                        type: "text"        },
      { value: "12/32",                          type: "tasks",      subLabel: "20 done"       },
      { value: "34/80",                          type: "tasks",      subLabel: "46 remaining"  },
      { value: "1 Mar 2025",                     type: "stacked",    subLabel: "14 May 2026"   },
      { value: "Active",                         type: "status"      },
    ],
  },
  {
    rowId: "J01041",
    atRisk: false,
    location: "Wellington",
    row: [
      { value: "J01041",                         type: "text"        },
      { value: "Kāpiti Mobile App v2",           type: "projectName", meta: { progress: 34 } },
      { value: "Kāpiti Council",                 type: "text"        },
      { value: "Rangi Parata",                   type: "pm"          },
      { value: "$75,000",                        type: "text"        },
      { value: "21/32",                          type: "tasks",      subLabel: "11 done"       },
      { value: "56/160",                         type: "tasks",      subLabel: "104 remaining" },
      { value: "12 Sep 2025",                    type: "stacked",    subLabel: "2 Jul 2026"    },
      { value: "Active",                         type: "status"      },
    ],
  },
  {
    rowId: "J01040",
    atRisk: true,
    location: "Auckland",
    row: [
      { value: "J01040",                         type: "text"        },
      { value: "Southern Cross CRM Integration", type: "projectName", meta: { progress: 52 } },
      { value: "Southern Cross",                 type: "text"        },
      { value: "Mele Tuilagi",                   type: "pm"          },
      { value: "$60,000",                        type: "text"        },
      { value: "7/32",                           type: "tasks",      subLabel: "25 remaining"  },
      { value: "4/120",                          type: "tasks",      subLabel: "116 remaining" },
      { value: "3 Nov 2025",                     type: "stacked",    subLabel: "30 Apr 2026"   },
      { value: "On Hold",                        type: "status"      },
    ],
  },
  {
    rowId: "J01039",
    atRisk: false,
    location: "Dunedin",
    row: [
      { value: "J01039",                         type: "text"        },
      { value: "Otago Vineyards E-commerce",     type: "projectName", meta: { progress: 81 } },
      { value: "Otago Vineyards",                type: "text"        },
      { value: "Aroha Smith",                    type: "pm"          },
      { value: "$45,000",                        type: "text"        },
      { value: "28/32",                          type: "tasks",      subLabel: "4 done"        },
      { value: "28/60",                          type: "tasks",      subLabel: "32 remaining"  },
      { value: "15 Jul 2025",                    type: "stacked",    subLabel: "28 Apr 2026"   },
      { value: "Active",                         type: "status"      },
    ],
  },
  {
    rowId: "J01038",
    atRisk: true,
    location: "Wellington",
    row: [
      { value: "J01038",                         type: "text"        },
      { value: "Wellington Transport Dashboard", type: "projectName", meta: { progress: 45 } },
      { value: "GWRC",                           type: "text"        },
      { value: "Sione Vaka",                     type: "pm"          },
      { value: "$50,000",                        type: "text"        },
      { value: "18/32",                          type: "tasks",      subLabel: "14 done"       },
      { value: "12/90",                          type: "tasks",      subLabel: "78 remaining"  },
      { value: "14 Jan 2026",                    type: "stacked",    subLabel: "10 Apr 2026"   },
      { value: "Late",                           type: "status"      },
    ],
  },
  {
    rowId: "J01037",
    atRisk: false,
    location: "Auckland",
    row: [
      { value: "J01037",                         type: "text"        },
      { value: "FreshCo POS Rollout",            type: "projectName", meta: { progress: 8 } },
      { value: "FreshCo Foods",                  type: "text"        },
      { value: "Rangi Parata",                   type: "pm"          },
      { value: "$90,000",                        type: "text"        },
      { value: "3/3",                            type: "tasks",      subLabel: "0 done"        },
      { value: "0/180",                          type: "tasks",      subLabel: "180 remaining" },
      { value: "5 Apr 2026",                     type: "stacked",    subLabel: "15 Sep 2026"   },
      { value: "Planning",                       type: "status"      },
    ],
  },
  {
    rowId: "J01036",
    atRisk: false,
    location: "Auckland",
    row: [
      { value: "J01036",                         type: "text"        },
      { value: "Auckland Uni Research Portal",   type: "projectName", meta: { progress: 72 } },
      { value: "Uni of Auckland",                type: "text"        },
      { value: "Mele Tuilagi",                   type: "pm"          },
      { value: "$55,000",                        type: "text"        },
      { value: "9/32",                           type: "tasks",      subLabel: "23 done"       },
      { value: "38/100",                         type: "tasks",      subLabel: "62 remaining"  },
      { value: "10 Jan 2025",                    type: "stacked",    subLabel: "20 Jun 2026"   },
      { value: "Active",                         type: "status"      },
    ],
  },
  {
    rowId: "J01035",
    atRisk: false,
    location: "Bay of Plenty",
    row: [
      { value: "J01035",                         type: "text"        },
      { value: "Bay of Plenty Tourism App",      type: "projectName", meta: { progress: 19 } },
      { value: "BOP Tourism Board",              type: "text"        },
      { value: "Sione Vaka",                     type: "pm"          },
      { value: "$32,000",                        type: "text"        },
      { value: "5/32",                           type: "tasks",      subLabel: "0 done"        },
      { value: "20/70",                          type: "tasks",      subLabel: "50 remaining"  },
      { value: "20 Mar 2026",                    type: "stacked",    subLabel: "1 Aug 2026"    },
      { value: "Planning",                       type: "status"      },
    ],
  },
  {
    rowId: "J01034",
    atRisk: false,
    location: "Hamilton",
    row: [
      { value: "J01034",                           type: "text"        },
      { value: "Waikato Hospital Patient Portal",  type: "projectName", meta: { progress: 61 } },
      { value: "Waikato DHB",                      type: "text"        },
      { value: "Aroha Smith",                      type: "pm"          },
      { value: "$120,000",                         type: "text"        },
      { value: "33/32",                            type: "tasks",      subLabel: "1 over"        },
      { value: "60/200",                           type: "tasks",      subLabel: "140 remaining" },
      { value: "15 Jan 2025",                      type: "stacked",    subLabel: "30 Nov 2026"   },
      { value: "Active",                           type: "status"      },
    ],
  },
];
